### ISSUE TITLE
Required command was not provided

### ISSUE THREAD

**Issue by extamyy** [kirrishima/BlumAutoFarm#10]
Required command was not provided. The provided API hash '**d3********12********82********' is not valid.

**Comment by kirrishima** [comment]
please provide full usage case. And keep in mind that you need to use commands, not just the options

**Comment by kirrishima** [comment]
Must be fixed in [this commit](https://github.com/kirrishima/BlumAutoFarm/commit/a86b3e6c41cd66386590e79eecdf3842983e7b8f)
