### ISSUE TITLE
PlayGameAsync doesn't work in FarmingService

### ISSUE THREAD

**Issue by lazypentester** [kirrishima/BlumAutoFarm#11]
PlayGameAsync doesn't work in FarmingService, because Blum now "hash or sign" the content that is sent when a snowflake game is completed. To be more precise, the ClaimGameAsync method does not work now.

BlumGameJson data = new()
            {
                GameId = gameId,
                Points = points
            };
            var jsonData = JsonSerializer.Serialize(data);

            var result = await _session.TryPostAsync(BlumUrls.GameClaim, jsonData);

The result of sending a request with a naked JSON will be OK, but the points for the game will not be counted.

![photo_2024-10-19_13-29-06](https://github.com/user-attachments/assets/6e702d59-705c-44ea-99c6-415af0ee408c)

**Comment by lazypentester** [comment]
Please confirm or deny this, maybe I don't understand something?

**Comment by kirrishima** [comment]
Blum team added encryption to protect from bots, so now they can only claim daily / farming reward and start farming. So now using raw json data is not acceptable. If you have a solution or will find repo on any programming language with working solution - please let me know

**Comment by kirrishima** [comment]
I had found a way to fix playing, thanks to [zuydd's database](https://github.com/zuydd/database/blob/main/blum.json) and [repo](https://github.com/zuydd/blum)
