### ISSUE TITLE
how i can start farm?

### ISSUE THREAD

**Issue by extamyy** [kirrishima/BlumAutoFarm#13]
C:\Users\extamyy\Desktop\blum>Blum.exe start-farm
10-20 17:55:56:5633 |  INFO   | Found 0 sessions.

C:\Users\extamyy\Desktop\blum>Blum.exe start-farm
10-20 17:56:18:8574 |  INFO   | Found 0 sessions.

C:\Users\extamyy\Desktop\blum>Blum.exe start-farm
10-20 17:56:30:1578 |  INFO   | Found 0 sessions.

**Comment by extamyy** [comment]
and when I run blum.exe, it automatically closes.

**Comment by kirrishima** [comment]
This is `CLI` program, so use it in cmd, don't run Blum.exe itself. Refer to [README.md](https://github.com/kirrishima/BlumAutoFarm/blob/main/README.md) for more info or use `-h` option to get list of all commands avilable
